version: "3.7"
name: report-notebook
services:
    app:
        container_name: project-rn
        build:
            context: ./
            dockerfile: Dockerfile
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - network

    adminer:
        container_name: adminer-rn
        image: adminer
        ports:
            - "7050:8080"
        networks:
            - network
    db:
        container_name: mariadb-rn
        image: mariadb:10.6.15
        environment:
            MYSQL_DATABASE: report_notebook
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_USER: root
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - network

    nginx:
        container_name: nginx-rn
        image: nginx:1.25-alpine
        ports:
            - "8010:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - network

networks:
    network:
        driver: bridge
